plugin:
    name: 'exposia.simplecontactform::lang.plugin.name'
    description: 'exposia.simplecontactform::lang.plugin.description'
    author: RapideSoftware
    icon: oc-icon-envelope
    homepage: ''
